[project]
name = "hospital-database"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=2.14.3",
    "langchain-mcp-adapters>=0.2.1",
]
